name:                urlShortener
version:             0.1.0.0
github:              "drewboardman/urlShortener"
license:             BSD3
author:              "drew boardman"
maintainer:          "drew.e.boardman@gmail.com"
copyright:           "2019 drew boardman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/drewboardman/urlShortener#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- warp
- text
- time
- servant
- servant-server
- random
- persistent
- persistent-template
- persistent-sqlite
- wai
- unliftio-core
- mtl
- monad-logger
- conduit

library:
  source-dirs: src

executables:
  urlShortener-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - urlShortener

tests:
  urlShortener-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - urlShortener
